export const EXPENSE_LIST_REQUEST='EXPENSE_LIST_REQUEST'
export const EXPENSE_LIST_SUCCESS='EXPENSE_LIST_SUCCESS'
export const EXPENSE_LIST_FAIL='EXPENSE_LIST_FAIL'

export const ADD_EXPENSE_LIST_REQUEST='ADD_EXPENSE_LIST_REQUEST'
export const ADD_EXPENSE_LIST_SUCCESS='ADD_EXPENSE_LIST_SUCCESS'
export const ADD_EXPENSE_LIST_FAIL='ADD_EXPENSE_LIST_FAIL'

export const EXPENSE_DELETE_REQUEST='EXPENSE_DELETE_REQUEST'
export const EXPENSE_DELETE_SUCCESS='EXPENSE_DELETE_SUCCESS'
export const EXPENSE_DELETE_FAIL='EXPENSE_DELETE_FAIL'
