export const INCOME_LIST_REQUEST='INCOME_LIST_REQUEST'
export const INCOME_LIST_SUCCESS='INCOME_LIST_SUCCESS'
export const INCOME_LIST_FAIL='INCOME_LIST_FAIL'

export const ADD_INCOME_LIST_REQUEST='ADD_INCOME_LIST_REQUEST'
export const ADD_INCOME_LIST_SUCCESS='ADD_INCOME_LIST_SUCCESS'
export const ADD_INCOME_LIST_FAIL='ADD_INCOME_LIST_FAIL'

export const INCOME_DELETE_REQUEST='INCOME_DELETE_REQUEST'
export const INCOME_DELETE_SUCCESS='INCOME_DELETE_SUCCESS'
export const INCOME_DELETE_FAIL='INCOME_DELETE_FAIL'
